"""
ATLAS - Inference Pipeline

Responsible for:
    Candidate pairs
        -> Feature engineering
        -> ML scoring
        -> Entity-level decisions
        -> Submission outputs

Does NOT handle:
    - Candidate generation
    - Blocking
    - Training
    - Threshold optimization
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd

from src.conflict_engine import ConflictEngine
from src.features import FeatureEngineer, get_feature_columns
from src.matcher import EntityMatcher
from src.output_generator import OutputGenerator


class InferencePipeline:
    """
    End-to-end inference pipeline for ATLAS.

    The pipeline assumes that candidate_pairs has already been
    generated by the blocking/candidate-generation module.

    Candidate generation is intentionally outside this class.
    """

    def __init__(
        self,
        feature_engineer: Optional[FeatureEngineer] = None,
        matcher: Optional[EntityMatcher] = None,
        threshold: float = 0.5,
        conflict_gap: float = 0.05,
        output_generator: Optional[OutputGenerator] = None,
    ) -> None:

        if not 0.0 <= threshold <= 1.0:
            raise ValueError(
                f"threshold must be between 0 and 1. Got {threshold}."
            )

        if conflict_gap < 0.0:
            raise ValueError(
                f"conflict_gap must be non-negative. Got {conflict_gap}."
            )

        self.feature_engineer = (
            feature_engineer
            if feature_engineer is not None
            else FeatureEngineer()
        )

        self.matcher = matcher

        self.conflict_engine = ConflictEngine(
            threshold=threshold,
            conflict_gap=conflict_gap,
        )

        self.output_generator = (
            output_generator
            if output_generator is not None
            else OutputGenerator()
        )

        self.threshold = threshold
        self.conflict_gap = conflict_gap

    def run(
        self,
        test_source1: pd.DataFrame,
        test_source2: pd.DataFrame,
        test_source3: pd.DataFrame,
        candidate_pairs: pd.DataFrame,
        output_dir: Optional[str | Path] = None,
    ) -> dict[str, object]:
        """
        Run complete inference pipeline.

        Parameters
        ----------
        test_source1:
            Test Source 1 dataframe.

        test_source2:
            Test Source 2 dataframe.

        test_source3:
            Test Source 3 dataframe.

        candidate_pairs:
            Candidate pairs produced by the blocking pipeline.

        output_dir:
            Optional directory for submission outputs.

        Returns
        -------
        dict
            Contains:
                - feature_table
                - scored_candidates
                - decisions
                - matching_results
                - candidate_output
        """

        self._validate_matcher()

        # ---------------------------------------------------------
        # 1. Feature engineering
        # ---------------------------------------------------------
        feature_table = self.feature_engineer.transform(
            source1=test_source1,
            source2=test_source2,
            source3=test_source3,
            candidate_pairs=candidate_pairs,
        )

        feature_columns = get_feature_columns()

        missing_features = [
            column
            for column in feature_columns
            if column not in feature_table.columns
        ]

        if missing_features:
            raise ValueError(
                "Feature table is missing required model columns: "
                f"{missing_features}"
            )

        # ---------------------------------------------------------
        # 2. Prepare model matrix
        # ---------------------------------------------------------
        X = feature_table[feature_columns].to_numpy(
            dtype=np.float32
        )

        if X.ndim != 2:
            raise ValueError(
                f"Expected 2D feature matrix. Got shape {X.shape}."
            )

        if not np.isfinite(X).all():
            raise ValueError(
                "Feature matrix contains NaN or infinite values."
            )

        # ---------------------------------------------------------
        # 3. ML scoring
        # ---------------------------------------------------------
        scores = self.matcher.predict_scores(X)

        if len(scores) != len(candidate_pairs):
            raise RuntimeError(
                "Number of model scores does not match candidate pairs. "
                f"Got {len(scores)} scores for "
                f"{len(candidate_pairs)} candidate pairs."
            )

        if not np.isfinite(scores).all():
            raise RuntimeError(
                "Matcher produced NaN or infinite scores."
            )

        if ((scores < 0.0) | (scores > 1.0)).any():
            raise RuntimeError(
                "Matcher produced probabilities outside [0, 1]."
            )

        # ---------------------------------------------------------
        # 4. Attach scores to candidate pairs
        # ---------------------------------------------------------
        scored_candidates = candidate_pairs[
            [
                "source1_entity_id",
                "candidate_entity_id",
                "candidate_source",
            ]
        ].copy()

        scored_candidates["score"] = scores

        # ---------------------------------------------------------
        # 5. Entity-level decision making
        # ---------------------------------------------------------
        decisions = self.conflict_engine.decide(
            scored_candidates
        )

        # ---------------------------------------------------------
        # 6. Generate final submission outputs
        # ---------------------------------------------------------
        if output_dir is not None:
            generator = OutputGenerator(output_dir)
        else:
            generator = self.output_generator

        matching_results, candidate_output = generator.generate(
            test_source1=test_source1,
            candidate_pairs=candidate_pairs,
            decisions=decisions,
        )

        return {
            "feature_table": feature_table,
            "scored_candidates": scored_candidates,
            "decisions": decisions,
            "matching_results": matching_results,
            "candidate_output": candidate_output,
        }

    def _validate_matcher(self) -> None:
        """Ensure a fitted matcher is available."""

        if self.matcher is None:
            raise ValueError(
                "No EntityMatcher was provided. "
                "Create a trained matcher and pass it to InferencePipeline."
            )

        if not getattr(self.matcher, "is_fitted", False):
            raise RuntimeError(
                "The supplied EntityMatcher has not been fitted."
            )